--- 
app: 
  description: "Welcome to ${app.name}"
  name: "My config app"
db: 
  connection: "{connectionString: 'https://___' , username: 'admin' , password:'password'}"
  host: "127.0.0.1"
  port: 1200
dbvalues: "{connectionString: 'https://___' , username: 'admin' , password:'password'}"
my: 
  greeting: "Welcome to configuration example"
  list: 
    values: "One,Two,Three,Four"

